export default class HomeTypes {
  static HOME_INCREMENT = 'HOME_INCREMENT';
  static HOME_DECREMENT = 'HOME_DECREMENT';
  static HOME_SETNUMBER = 'HOME_SETNUMBER';
  static HOME_APPLYNUMBER = 'HOME_APPLYNUMBER';
  static HOME_RESET = 'HOME_RESET';
}
